resources:
- cluster-api-cleaner-cloud-director.yaml
- cluster-api-provider-cloud-director.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-route53.yaml
- etcd-backup-operator.yaml
- event-exporter-app.yaml
- exception-recommender.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- konfiguration.v2.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
