resources:
- cluster-api-cleaner-cloud-director.yaml
- cluster-api-events.yaml
- cluster-api-provider-cloud-director.yaml
- cluster-api.yaml
- dashboards.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-route53.yaml
- encryption-provider-operator.yaml
- etcd-backup-operator.yaml
- event-exporter-app.yaml
- exception-recommender.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- grafana.yaml
- image-distribution-operator.yaml
- ingress-nginx.yaml
- keda.yaml
- konfiguration.v2.yaml
- kube-downscaler.yaml
- kyverno-policies-connectivity.yaml
- kyverno-policies-dx.yaml
- kyverno-policies-observability.yaml
- kyverno-policies-ux.yaml
- loki.yaml
- mimir.yaml
- oauth2-proxy.yaml
- observability-operator.yaml
- observability-platform-api.yaml
- organization-operator.yaml
- plugin-barman-cloud.yaml
- prometheus-remotewrite.yaml
- rbac-operator.yaml
- silence-operator.yaml
- sloth-rules.yaml
- sloth.yaml
- starboard-exporter.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
