resources:
- cluster-api-cleaner-cloud-director.yaml
- cluster-api-provider-cloud-director.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-route53.yaml
- event-exporter-app.yaml
- konfiguration.v2.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- trivy-operator.yaml
